server:
  port: 18081
# 系统参数 信息
data:
  # 域名设置 跨域
  allowedOrigin: '*'
  # 直接访问 http://localhost:18081 时 返回信息设置
  indexView: '请访问：http://localhost:18081/swagger-ui.html  查看API文档'
  dictUrl: http://localhost:18080/api/v1/dict/dictName

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.132.136.225:3306/photo_manage?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true&autoReconnect=true
      username: root
      password: root@123
      # 连接池配置
      initial-size: 10
      max-active: 20
      #  min-evictable-idle-time-millis: 30000
      # max-evictable-idle-time-millis: 30000
      max-open-prepared-statements: 60000
      max-pool-prepared-statement-per-connection-size: 10
      max-wait: 60000
      min-idle: 5
      pool-prepared-statements: true
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      transaction-threshold-millis: 60000
      remove-abandoned-timeout-millis: 30000
      filters: stat,wall,log4j2  # 配置监控统计拦截的filters,采用log4j2作为日志实现
      # 监控配置　WebStatFilter配置
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        principal-cookie-name: admin
        principal-session-name: admin
        profile-enable: true
        session-stat-enable: false
        session-stat-max-count: 1000
        url-pattern: '/*'
      stat-view-servlet:
        allow: 127.0.0.1  # IP 白名单
        deny: 192.168.0.10 #  IP黑名单(共同存在时，deny优先于allow)
        enabled: true
        login-password: admin  # 控制台用户名和密码
        login-username: admin
        reset-enable: false
        url-pattern: '/druid/*'
      # 配置日志输出
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false

  # elasticsearch 配置
  data:
    elasticsearch:
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 101.132.136.225:9300
      # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: docker-cluster
      properties:
        path:
          logs: ./elasticsearch/log # elasticsearch日志存储目录
          data: ./elasticsearch/data # elasticsearch数据存储目录
        transport:
          tcp:
            connect_timeout: 120s  # 连接超时的时间

  # redis 配置
  redis:
    host: 101.132.136.225
    port: 6379
    password:
    database: 1
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1ms
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 60000ms